const LEARN_KEY='shanghan_learning_v1';
const LEARN_METHODS=[
['经典熟读','核心经典反复读、重点条文做到随时能调出来；不是读过一次就算完成。'],
['读记并行','读到疑问、领悟、鉴别点立即记下，逐渐把散点变成自己的专题索引。'],
['先辨后看','看医案或方证前先独立判断，再看原文与医家解释，专门比较自己哪里想错。'],
['临证返经典','遇到一个真实问题，回头查经典同类条文；再拿经典重新解释当前问题。'],
['阶段复盘','把误判、犹豫和没有解释清的地方集中复盘，而不是只收藏“正确答案”。'],
['博采而有定见','明确区分仲景原文、后世注家、现代解释和自己的经验，比较后再形成暂时结论。']
];
function loadLearning(){try{return JSON.parse(localStorage.getItem(LEARN_KEY)||'{}')}catch{return{}}}
function saveLearning(s){localStorage.setItem(LEARN_KEY,JSON.stringify(s));}
function allClassicCards(){return Object.entries(CLASSIC_SOURCES||{}).flatMap(([formula,refs])=>refs.map((r,i)=>({formula,i,...r})));}
function randomClassic(){const a=allClassicCards();return a[Math.floor(Math.random()*a.length)];}
function renderMethods(){const el=document.getElementById('learnMethods');if(!el)return;el.innerHTML=LEARN_METHODS.map(([t,d])=>`<div class="learn-method"><b>${t}</b><p>${d}</p></div>`).join('');}
function renderRecall(){const el=document.getElementById('recallCard');if(!el)return;const r=randomClassic();if(!r)return;el.dataset.formula=r.formula;el.dataset.quote=r.quote;el.innerHTML=`<div class="recall-head"><div><span class="badge">经典回忆</span><h3>${r.formula}</h3></div><button id="nextRecall" class="mini-btn">换一条</button></div><p class="recall-prompt">先别看原文：回忆这个方最关键的证、脉、鉴别点，以及你能记起的条文。</p><div class="recall-actions"><button id="showRecall" class="mini-btn primary">显示原文</button><button id="markRecall" class="mini-btn">加入待复盘</button></div><div id="recallAnswer" class="recall-answer" hidden><div class="classic-head"><span>${r.kind}</span><a href="${r.url}" target="_blank" rel="noopener">${r.book} ↗</a></div><blockquote>${typeof linkifyTerms==='function'?linkifyTerms(r.quote):r.quote}</blockquote><p>${r.note}</p></div>`;document.getElementById('nextRecall').onclick=renderRecall;document.getElementById('showRecall').onclick=()=>{document.getElementById('recallAnswer').hidden=false;if(typeof bindTermLinks==='function')bindTermLinks(el)};document.getElementById('markRecall').onclick=()=>{const s=loadLearning();s.review=s.review||[];const item={formula:r.formula,quote:r.quote,book:r.book,at:Date.now()};if(!s.review.some(x=>x.formula===item.formula&&x.quote===item.quote))s.review.unshift(item);saveLearning(s);renderReviewCount();};}
function renderReviewCount(){const s=loadLearning();const n=(s.review||[]).length;const el=document.getElementById('reviewCount');if(el)el.textContent=`待复盘 ${n} 条`;}
function formulaNameFromCard(card){const h=card.querySelector('.rhead h3');if(!h)return'';return (h.childNodes[0]?.textContent||h.textContent).replace(/^\d+\.\s*/,'').trim();}
function attachLearningTools(){document.querySelectorAll('.result').forEach(card=>{if(card.querySelector('.learn-tools'))return;const name=formulaNameFromCard(card);if(!name)return;const box=document.createElement('div');box.className='learn-tools';box.innerHTML=`<div class="learn-tool-head"><b>学习训练</b><span>不要只看答案，先解释你的判断。</span></div><div class="think-grid"><div><b>① 为什么是它？</b><p>哪 2–3 个证据最有辨识度？</p></div><div><b>② 为什么不是相近方？</b><p>哪一个症状或脉象真正决定分界？</p></div><div><b>③ 什么会推翻它？</b><p>出现哪条反证时应立刻重新辨？</p></div></div><div class="learn-actions"><button class="mini-btn toggle-quotes">遮住/显示原文</button><button class="mini-btn mark-review">待复盘</button><button class="mini-btn note-toggle">我的按语</button></div><div class="formula-note" hidden><textarea placeholder="写下你自己的理解：关键证、与相近方的分界、仍不明白的地方……"></textarea><div><button class="mini-btn save-note">保存到本机</button></div></div>`;card.appendChild(box);const quotes=card.querySelectorAll('.classics blockquote');box.querySelector('.toggle-quotes').onclick=()=>quotes.forEach(q=>q.classList.toggle('quote-hidden'));box.querySelector('.mark-review').onclick=()=>{const s=loadLearning();s.review=s.review||[];if(!s.review.some(x=>x.formula===name&&!x.quote))s.review.unshift({formula:name,at:Date.now()});saveLearning(s);renderReviewCount();};const note=box.querySelector('.formula-note'),ta=note.querySelector('textarea');const s=loadLearning();ta.value=(s.notes||{})[name]||'';box.querySelector('.note-toggle').onclick=()=>note.hidden=!note.hidden;box.querySelector('.save-note').onclick=()=>{const st=loadLearning();st.notes=st.notes||{};st.notes[name]=ta.value;saveLearning(st);box.querySelector('.save-note').textContent='已保存';setTimeout(()=>box.querySelector('.save-note').textContent='保存到本机',1000);};});}
function installLearningHook(){const btn=document.getElementById('calc');if(!btn)return;const old=btn.onclick;btn.onclick=()=>{old&&old();attachLearningTools();};}
renderMethods();renderRecall();renderReviewCount();installLearningHook();
