const repoBookCache=new Map();let localBooks=[];let readerState={book:null,start:0,size:320,query:''};
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('tcm-local-library',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('books'))r.result.createObjectStore('books',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function dbAll(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction('books').objectStore('books').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});}
async function dbPut(book){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction('books','readwrite');t.objectStore('books').put(book);t.oncomplete=res;t.onerror=()=>rej(t.error);});}
async function dbDelete(id){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction('books','readwrite');t.objectStore('books').delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error);});}
async function loadRepoBooks(){await Promise.all(BOOK_MANIFEST.map(async b=>{try{const r=await fetch(b.path,{cache:'no-store'});if(r.ok){const text=await r.text();repoBookCache.set(b.id,{...b,text,origin:'repo'});}}catch{}}));}
function allBooks(){const m=new Map([...repoBookCache.values()].map(b=>[b.id,b]));localBooks.forEach(b=>m.set(b.id,b));return [...m.values()];}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function bookTitleFromFile(name){return name.replace(/\.txt$/i,'').replace(/[-_]/g,' ');}
function setView(name){document.querySelectorAll('.app-view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));document.querySelectorAll('.mode-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));location.hash=name;}
window.openLocalSearch=function(term){setView('search');const input=document.getElementById('librarySearch');input.value=term;runLibrarySearch();input.focus();};
function renderBooks(){const box=document.getElementById('localBookList');if(!box)return;const installed=new Map(allBooks().map(b=>[b.id,b]));const manifestCards=BOOK_MANIFEST.map(b=>{const got=installed.get(b.id);return `<button class="book-card ${got?'ready':'pending'}" data-book="${b.id}" ${got?'':'disabled'}><b>${b.title}</b><span>${b.author} · ${b.edition}</span><small>${got?'本地 TXT 已装入':'待装入 '+b.path}</small></button>`;});const userCards=localBooks.filter(b=>!BOOK_MANIFEST.some(m=>m.id===b.id)).map(b=>`<div class="book-card ready user-book"><button data-book="${b.id}"><b>${esc(b.title)}</b><span>我的本地 TXT</span><small>${Math.round((b.text||'').length/1000)}k 字符</small></button><button class="book-delete" data-delete-book="${b.id}" title="移除">×</button></div>`);box.innerHTML=manifestCards.join('')+userCards.join('');box.querySelectorAll('[data-book]:not([disabled])').forEach(b=>b.onclick=()=>openBook(b.dataset.book));box.querySelectorAll('[data-delete-book]').forEach(b=>b.onclick=async()=>{await dbDelete(b.dataset.deleteBook);localBooks=await dbAll();renderBooks();});document.getElementById('bookStats').textContent=`已装入 ${allBooks().length} 本 · 目录规划 ${BOOK_MANIFEST.length} 本`;}
function getBook(id){return allBooks().find(b=>b.id===id);}
function lineArray(book){return (book.text||'').replace(/\r\n/g,'\n').split('\n');}
function highlightPlain(text,q){let out=esc(text);if(q){const terms=q.split(/[\s+，,]+/).filter(Boolean).sort((a,b)=>b.length-a.length);terms.forEach(t=>{const safe=t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');out=out.replace(new RegExp(safe,'gi'),m=>`<mark>${m}</mark>`);});}return out;}
function readerLineHtml(line){return typeof linkifyTerms==='function'?linkifyTerms(line):esc(line);}
function renderReader(){const {book,start,size}=readerState;if(!book)return;const lines=lineArray(book),end=Math.min(lines.length,start+size),body=document.getElementById('readerBody');document.getElementById('readerTitle').textContent=book.title;document.getElementById('readerMeta').textContent=`${book.author||'本地资料'} · ${book.edition||''} · 第 ${start+1}-${end} 行 / ${lines.length}`;body.innerHTML=lines.slice(start,end).map((line,i)=>`<p class="reader-line" data-line="${start+i+1}"><span>${start+i+1}</span>${readerLineHtml(line)}</p>`).join('');if(typeof bindTermLinks==='function')bindTermLinks(body);document.getElementById('readerPrev').disabled=start<=0;document.getElementById('readerNext').disabled=end>=lines.length;document.getElementById('readerPanel').hidden=false;}
function openBook(id,line=0,q=''){const book=getBook(id);if(!book)return;setView('library');readerState={book,start:Math.max(0,line-80),size:320,query:q};renderReader();document.getElementById('readerPanel').scrollIntoView({behavior:'smooth',block:'start'});}
function searchInBook(book,terms){const lines=lineArray(book),hits=[];for(let i=0;i<lines.length&&hits.length<50;i++){const line=lines[i].trim();if(!line)continue;if(terms.every(t=>line.includes(t)))hits.push({book,line:i,text:line});}return hits;}
function runLibrarySearch(){const q=document.getElementById('librarySearch').value.trim(),box=document.getElementById('searchResults');if(!q){box.innerHTML='<div class="empty">输入关键词，支持“口渴 + 小便不利”这类共现搜索。</div>';return;}const terms=q.split(/[\s+，,]+/).filter(Boolean),hits=allBooks().flatMap(b=>searchInBook(b,terms).map(h=>({...h,bookObj:b})));let notes=[];try{notes=Object.entries(JSON.parse(localStorage.getItem('tcm_experience_notes')||'{}')).filter(([,v])=>terms.every(t=>String(v).includes(t)));}catch{}box.innerHTML=`<div class="search-summary">本地古籍命中 ${hits.length} 条${notes.length?` · 我的经验 ${notes.length} 条`:''}</div>`+(hits.length?hits.slice(0,150).map(h=>`<button class="search-hit" data-book="${h.bookObj.id}" data-line="${h.line}" data-q="${esc(q)}"><b>${h.bookObj.title}</b><span>第 ${h.line+1} 行</span><p>${highlightPlain(h.text,q)}</p></button>`).join(''):'<div class="empty">当前已装入 TXT 中没有同时命中这些词。</div>')+(notes.length?`<div class="note-hits"><h3>我的经验</h3>${notes.map(([,v])=>`<div>${highlightPlain(v,q)}</div>`).join('')}</div>`:'');box.querySelectorAll('.search-hit').forEach(b=>b.onclick=()=>openBook(b.dataset.book,Number(b.dataset.line),b.dataset.q));}
async function importTxt(files){for(const file of files){const text=await file.text(),match=BOOK_MANIFEST.find(m=>m.path.endsWith('/'+file.name));const book=match?{...match,text,origin:'browser',filename:file.name,addedAt:Date.now()}:{id:'user:'+file.name,title:bookTitleFromFile(file.name),text,origin:'browser',filename:file.name,addedAt:Date.now()};await dbPut(book);}localBooks=await dbAll();renderBooks();}
function bindLibraryUI(){document.querySelectorAll('.mode-nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.getElementById('librarySearchBtn').onclick=runLibrarySearch;document.getElementById('librarySearch').addEventListener('keydown',e=>{if(e.key==='Enter')runLibrarySearch();});document.getElementById('txtImport').onchange=e=>importTxt([...e.target.files]);document.getElementById('readerPrev').onclick=()=>{readerState.start=Math.max(0,readerState.start-readerState.size);renderReader();};document.getElementById('readerNext').onclick=()=>{readerState.start+=readerState.size;renderReader();};document.getElementById('readerFind').addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.trim();if(!q||!readerState.book)return;const lines=lineArray(readerState.book),idx=lines.findIndex((x,i)=>i>readerState.start&&x.includes(q));if(idx>=0){readerState.start=Math.max(0,idx-40);readerState.query=q;renderReader();}}});document.addEventListener('click',e=>{const a=e.target.closest?.('.term-more a');if(a){e.preventDefault();const m=a.textContent.match(/“(.+?)”/);if(m)openLocalSearch(m[1]);}});}
(async()=>{await loadRepoBooks();try{localBooks=await dbAll();}catch{localBooks=[];}renderBooks();bindLibraryUI();const initial=location.hash.replace('#','');setView(['library','search','diagnosis'].includes(initial)?initial:'diagnosis');})();
