const repoBookCache=new Map();let localBooks=[];let pagefindPromise=null;let openccPromise=null;let renderSeq=0;let readerState={book:null,start:0,size:320,query:''};
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('tcm-local-library',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('books'))r.result.createObjectStore('books',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function dbAll(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction('books').objectStore('books').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});}
async function dbPut(book){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction('books','readwrite');t.objectStore('books').put(book);t.oncomplete=res;t.onerror=()=>rej(t.error);});}
async function dbDelete(id){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction('books','readwrite');t.objectStore('books').delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error);});}
function repoBooks(){return (typeof BOOK_MANIFEST==='undefined'?[]:BOOK_MANIFEST).map(b=>({...b,origin:'repo'}));}
function allBooks(){const m=new Map(repoBooks().map(b=>[b.id,b]));localBooks.forEach(b=>m.set(b.id,b));return [...m.values()];}
function getBook(id){return localBooks.find(b=>b.id===id)||repoBookCache.get(id)||repoBooks().find(b=>b.id===id);}
async function ensureBook(book){if(!book)return null;if(book.text)return book;if(repoBookCache.has(book.id))return repoBookCache.get(book.id);const r=await fetch(book.path);if(!r.ok)throw new Error(`古籍正文加载失败 ${r.status}`);const full={...book,text:await r.text(),origin:'repo'};repoBookCache.set(book.id,full);return full;}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function bookTitleFromFile(name){return name.replace(/\.txt$/i,'').replace(/[-_]/g,' ');}
function setView(name){document.querySelectorAll('.app-view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));document.querySelectorAll('.mode-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));location.hash=name;}
window.openLocalSearch=function(term){setView('search');const input=document.getElementById('librarySearch');input.value=term;runLibrarySearch();input.focus();};
async function getConverters(){if(!openccPromise)openccPromise=import('./vendor/opencc-js/full.js').then(m=>{const O=m.default||m;return {s2t:O.Converter({from:'cn',to:'tw'}),t2s:O.Converter({from:'tw',to:'cn'})};});return openccPromise;}
async function queryVariants(q){const out=[String(q||'').trim()].filter(Boolean);try{const c=await getConverters();out.push(c.s2t(q),c.t2s(q));}catch(e){console.warn('OpenCC unavailable',e);}return [...new Set(out.filter(Boolean))];}
function bookMatches(b,variants){if(!variants.length)return true;const s=[b.title,b.author,b.category,b.edition].join(' ').toLowerCase();return variants.some(v=>v.split(/\s+/).every(x=>s.includes(x.toLowerCase())));}
function captureLabel(b){if(b.origin==='browser')return '我的本地 TXT';return b.captureStatus||(b.complete===false?'部分抓取':b.expanded?'分卷收录':'单页收录');}
function splitStatus(b){if(!b.subpagesTotal)return '';const accounted=(b.subpagesFetched||0)+(b.subpagesEmpty||0);return ` · 分卷 ${accounted}/${b.subpagesTotal}${b.subpagesFailed?` · 失败 ${b.subpagesFailed}`:''}`;}
async function renderBooks(filter=''){const seq=++renderSeq,variants=filter?await queryVariants(filter):[];if(seq!==renderSeq)return;const box=document.getElementById('localBookList');if(!box)return;const books=allBooks().filter(b=>bookMatches(b,variants));box.innerHTML=books.map(b=>b.origin==='browser'?`<div class="book-card ready user-book"><button data-book="${b.id}"><b>${esc(b.title)}</b><span>我的本地 TXT</span><small>${Math.round((b.text||'').length/1000)}k 字符</small></button><button class="book-delete" data-delete-book="${b.id}" title="移除">×</button></div>`:`<button class="book-card ready" data-book="${b.id}"><b>${esc(b.title)}</b><span>${esc(b.author||b.category||'古代医籍')}</span><small>${esc(b.category||'综合医籍')} · ${Math.round((b.chars||0)/1000)}k 字符 · ${esc(captureLabel(b))}${esc(splitStatus(b))}</small></button>`).join('')||'<div class="empty">没有匹配的书目。</div>';box.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>openBook(b.dataset.book));box.querySelectorAll('[data-delete-book]').forEach(b=>b.onclick=async e=>{e.stopPropagation();await dbDelete(b.dataset.deleteBook);localBooks=await dbAll();renderBooks(document.getElementById('bookFilter')?.value||'');});const stats=document.getElementById('bookStats');if(stats){const repo=repoBooks(),totalChars=repo.reduce((s,b)=>s+(b.chars||0),0);stats.textContent=`古籍库 ${repo.length} 部/篇 · 约 ${Math.round(totalChars/10000).toLocaleString()} 万字符 · 我的 TXT ${localBooks.length} 本`;}}
function lineArray(book){return (book.text||'').replace(/\r\n/g,'\n').split('\n');}
function linkFormulaNames(html){if(typeof FORMULA_DATA==='undefined')return html;return Object.keys(FORMULA_DATA).sort((a,b)=>b.length-a.length).reduce((out,name)=>out.replace(new RegExp(name,'g'),`<button class="formula-link" type="button" data-formula="${name}">${name}</button>`),html);}
function readerLineHtml(line){let out=typeof linkifyTerms==='function'?linkifyTerms(line):esc(line);return linkFormulaNames(out);}
function renderReader(){const {book,start,size}=readerState;if(!book)return;const lines=lineArray(book),end=Math.min(lines.length,start+size),body=document.getElementById('readerBody'),meta=document.getElementById('readerMeta');document.getElementById('readerTitle').textContent=book.title;const provenance=book.origin==='repo'?` · ${esc(captureLabel(book))}${esc(splitStatus(book))}${book.sourceUrl?` · <a href="${esc(book.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(book.source||'原始来源')}</a>`:''}`:'';meta.innerHTML=`${esc(book.author||book.category||'古籍')} · ${esc(book.edition||'')}${provenance} · 第 ${start+1}-${end} 行 / ${lines.length}`;body.innerHTML=lines.slice(start,end).map((line,i)=>`<p class="reader-line" data-line="${start+i+1}"><span>${start+i+1}</span>${readerLineHtml(line)}</p>`).join('');if(typeof bindTermLinks==='function')bindTermLinks(body);body.querySelectorAll('.formula-link').forEach(b=>b.onclick=()=>openCompareFor(b.dataset.formula));document.getElementById('readerPrev').disabled=start<=0;document.getElementById('readerNext').disabled=end>=lines.length;document.getElementById('readerPanel').hidden=false;}
async function bestLine(lines,q){const variants=await queryVariants(q);for(const v of variants){const terms=v.split(/[\s+，,]+/).filter(Boolean);let idx=lines.findIndex(x=>terms.every(t=>x.includes(t)));if(idx>=0)return idx;}for(const v of variants){const t=v.split(/[\s+，,]+/).filter(Boolean)[0];if(t){const idx=lines.findIndex(x=>x.includes(t));if(idx>=0)return idx;}}return 0;}
async function openBook(id,line=0,q=''){let book=getBook(id);if(!book)return;setView('library');const body=document.getElementById('readerBody');body.innerHTML='<div class="empty">正在载入原文…</div>';document.getElementById('readerPanel').hidden=false;try{book=await ensureBook(book);const lines=lineArray(book);if(q&&!line)line=await bestLine(lines,q);readerState={book,start:Math.max(0,Number(line||0)-60),size:320,query:q};renderReader();document.getElementById('readerPanel').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){body.innerHTML=`<div class="danger">${esc(e.message)}</div>`;}}
function searchInBook(book,terms){const lines=lineArray(book),hits=[];for(let i=0;i<lines.length&&hits.length<50;i++){const line=lines[i].trim();if(line&&terms.every(t=>line.includes(t)))hits.push({book,line:i,text:line});}return hits;}
async function getPagefind(){if(!pagefindPromise)pagefindPromise=import('./pagefind/pagefind.js').then(async p=>{await p.init();return p;});return pagefindPromise;}
async function corpusSearch(q){try{const pf=await getPagefind(),variants=await queryVariants(q),merged=new Map();for(const v of variants){const s=await pf.search(v);const rows=await Promise.all(s.results.slice(0,70).map(async r=>{const d=await r.data();return {bookId:d.meta?.book_id,title:d.meta?.title||'古籍',category:d.meta?.category||'',excerpt:d.excerpt||d.plain_excerpt||''};}));for(const row of rows){if(row.bookId&&!merged.has(row.bookId))merged.set(row.bookId,row);}}return [...merged.values()].slice(0,140);}catch(e){console.warn('Pagefind unavailable',e);return [];}}
window.corpusSearch=corpusSearch;
window.openCorpusBook=openBook;
async function runLibrarySearch(){const q=document.getElementById('librarySearch').value.trim(),box=document.getElementById('searchResults');if(!q){box.innerHTML='<div class="empty">输入关键词，支持“口渴 + 小便不利”这类共现搜索。</div>';return;}box.innerHTML='<div class="empty">正在检索古籍索引…</div>';const variants=await queryVariants(q),[corpusHits]=await Promise.all([corpusSearch(q)]);const localHits=[];for(const b of localBooks){const seen=new Set();for(const v of variants){for(const h of searchInBook(b,v.split(/[\s+，,]+/).filter(Boolean))){const k=h.line;if(!seen.has(k)){seen.add(k);localHits.push({...h,bookObj:b});}}}}let notes=[];try{notes=Object.entries(JSON.parse(localStorage.getItem('tcm_experience_notes')||'{}')).filter(([,v])=>variants.some(qv=>qv.split(/[\s+，,]+/).filter(Boolean).every(t=>String(v).includes(t))));}catch{}
  const corpusHtml=corpusHits.map(h=>`<button class="search-hit" data-book="${esc(h.bookId)}" data-q="${esc(q)}"><b>${esc(h.title)}</b><span>${esc(h.category)}</span><p>${h.excerpt}</p></button>`).join('');const localHtml=localHits.slice(0,80).map(h=>`<button class="search-hit" data-book="${h.bookObj.id}" data-line="${h.line}" data-q="${esc(q)}"><b>${esc(h.bookObj.title)}</b><span>我的 TXT · 第 ${h.line+1} 行</span><p>${esc(h.text)}</p></button>`).join('');box.innerHTML=`<div class="search-summary">古籍索引命中 ${corpusHits.length} 本 · 我的 TXT 命中 ${localHits.length} 条${notes.length?` · 我的经验 ${notes.length} 条`:''}</div>`+(corpusHtml+localHtml||'<div class="empty">没有命中。</div>')+(notes.length?`<div class="note-hits"><h3>我的经验</h3>${notes.map(([,v])=>`<div>${esc(v)}</div>`).join('')}</div>`:'');box.querySelectorAll('.search-hit').forEach(b=>b.onclick=()=>openBook(b.dataset.book,Number(b.dataset.line||0),b.dataset.q));}
async function importTxt(files){for(const file of files){const text=await file.text(),book={id:'user:'+file.name,title:bookTitleFromFile(file.name),text,origin:'browser',filename:file.name,addedAt:Date.now()};await dbPut(book);}localBooks=await dbAll();renderBooks(document.getElementById('bookFilter')?.value||'');}
function bindLibraryUI(){document.querySelectorAll('.mode-nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.getElementById('librarySearchBtn').onclick=runLibrarySearch;document.getElementById('librarySearch').addEventListener('keydown',e=>{if(e.key==='Enter')runLibrarySearch();});document.getElementById('txtImport').onchange=e=>importTxt([...e.target.files]);document.getElementById('bookFilter')?.addEventListener('input',e=>renderBooks(e.target.value.trim()));document.getElementById('readerPrev').onclick=()=>{readerState.start=Math.max(0,readerState.start-readerState.size);renderReader();};document.getElementById('readerNext').onclick=()=>{readerState.start+=readerState.size;renderReader();};document.getElementById('readerFind').addEventListener('keydown',async e=>{if(e.key==='Enter'){const q=e.target.value.trim();if(!q||!readerState.book)return;const lines=lineArray(readerState.book),idx=await bestLine(lines,q);if(idx>=0){readerState.start=Math.max(0,idx-40);readerState.query=q;renderReader();}}});document.addEventListener('click',e=>{const a=e.target.closest?.('.term-more a');if(a){e.preventDefault();const m=a.textContent.match(/“(.+?)”/);if(m)openLocalSearch(m[1]);}});}
(async()=>{try{localBooks=await dbAll();}catch{localBooks=[];}renderBooks();bindLibraryUI();const initial=location.hash.replace('#','');setView(['library','search','diagnosis'].includes(initial)?initial:'diagnosis');})();
